#!/bin/bash

dpkg --add-architecture i386 && apt-get install win32 
winecfg
wget https://www.python.org/ftp/python/2.7.13/python-2.7.msi
wine msiexec /i python-2.7.13.msi
wget https://bootstrap.pypa.io/get-pip.py
wine /root/.wine/drive_c/Python27/python.exe get-pip.py
wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller
